import { COLORS } from "./colors.js";

export const s = {
  app: {
    display: "flex",
    minHeight: "100vh",
    background: COLORS.bg,
    fontFamily: "'DM Mono', 'Courier New', monospace",
    color: COLORS.textPrimary,
    fontSize: 13,
  },
  sidebar: {
    width: 200,
    minHeight: "100vh",
    background: COLORS.surface,
    borderRight: `1px solid ${COLORS.border}`,
    padding: "24px 0",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
  },
  logo: {
    padding: "0 20px 24px",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.12em",
    color: COLORS.accent,
    textTransform: "uppercase",
    borderBottom: `1px solid ${COLORS.border}`,
    marginBottom: 8,
  },
  navItem: (active) => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 20px",
    cursor: "pointer",
    color: active ? COLORS.textPrimary : COLORS.textSecondary,
    background: active ? COLORS.accentDim : "transparent",
    borderLeft: `2px solid ${active ? COLORS.accent : "transparent"}`,
    transition: "all 0.15s",
    fontSize: 12,
    letterSpacing: "0.04em",
  }),
  main: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  topbar: {
    background: COLORS.surface,
    borderBottom: `1px solid ${COLORS.border}`,
    padding: "14px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topbarTitle: {
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: "0.06em",
    color: COLORS.textPrimary,
  },
  topbarSub: { fontSize: 11, color: COLORS.textSecondary, marginTop: 2 },
  content: { flex: 1, padding: 24, overflow: "auto" },
  card: {
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
  },
  btn: (variant = "primary") => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 14px",
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    fontSize: 12,
    fontFamily: "inherit",
    fontWeight: 600,
    letterSpacing: "0.04em",
    background: variant === "primary" ? COLORS.accent : COLORS.border,
    color: variant === "primary" ? "#fff" : COLORS.textSecondary,
    transition: "all 0.15s",
  }),
  tag: (color) => ({
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.08em",
    background: color + "20",
    color: color,
    textTransform: "uppercase",
  }),
  input: {
    width: "100%",
    background: COLORS.bg,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 6,
    padding: "8px 12px",
    color: COLORS.textPrimary,
    fontFamily: "inherit",
    fontSize: 12,
    outline: "none",
    boxSizing: "border-box",
  },
  label: {
    fontSize: 10,
    color: COLORS.textSecondary,
    marginBottom: 4,
    display: "block",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  filterBar: {
    display: "flex",
    gap: 6,
    marginBottom: 16,
    flexWrap: "wrap",
  },
};